version: "3.7"
services:
  webapp:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
    env_file:
      - secrets.env
